# Generated by Django 4.2.3 on 2023-08-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_tiposervicio_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img_servicios'),
        ),
    ]
