# Generated by Django 4.2.3 on 2023-07-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('documento', models.IntegerField(blank=True, max_length=8, null=True)),
                ('contacto', models.IntegerField(blank=True, max_length=15, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('nacimiento', models.DateField(null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ciudad')),
            ],
        ),
    ]
