# Generated by Django 4.2.3 on 2023-07-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ciudad',
            new_name='ciudad_id',
        ),
    ]
