# Generated by Django 4.2.3 on 2023-08-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
